# Generated by Django 3.0.1 on 2019-12-29 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='nmae',
            new_name='name',
        ),
    ]
